name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.DATABASE_UPDATE }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to project
    steps:
    - name: Assign NEW issues to project 1
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/aaaapartment/projects/1'
