name: Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".actrc"
      - ".gitignore"
      - "*.md"

jobs:
  deploy:
    if: |
      github.ref_name == 'main' &&
      github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cargo
          sudo apt-get install python3

      - name: Build executable
        run: |
          cd accounter
          cargo build -r

      - name: Upload executable to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: accounter
          path: ./target/release/accounter


