name: Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/*"
      - ".actrc"
      - ".gitignore"
      - "*.md"
  pull_request:
    branches:
      - main
    types:
      - opened
    paths:
      - "*.csv"

jobs:
  deploy:
    if: |
      github.event_name == 'push' &&
      github.event.pull_request.merged == false &&
      github.ref_name == 'main' &&
      github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cargo
          sudo apt-get install python3

      - name: Build executable
        run: |
          cd accounter
          cargo build -r

      - name: Tag release
        id: release-tag
        uses: phish108/autotag-action@1.1.51
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release-tag.outputs.new-tag }}
          files: |
            ./accounter/target/release/accounter

  validate-input:
    if: |
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          fileName: "accounter"
          out-file-path: "./accounter-exe"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.1

      - name: Validate changed files
        run: |
          chmod +x ./accounter-exe/accounter
          CHANGED=${{ steps.changed-files.outputs.all_changed_files }}
          NUM_CHANGED=$(wc -w <<< "$CHANGED")
          if [ $NUM_CHANGED -ne 1 ]; then
            echo "::error Too many files - only submit one file"
            exit 1
          fi
          ./accounter-exe/accounter --database ./account.sqlite --filename $CHANGED --user ${{ github.event.pull_request.user.login }} --validate

  update-database:
    if: |
      github.event_name == 'push' &&
      github.event.pull_request.merged == true &&
      github.ref_name == 'main' &&
      github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          fileName: "accounter"
          out-file-path: "./accounter-exe"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.1

      - name: Update database
        run: |
          chmod +x ./accounter-exe/accounter
          CHANGED=${{ steps.changed-files.outputs.all_changed_files }}
          NUM_CHANGED=$(wc -w <<< "$CHANGED")
          if [ $NUM_CHANGED -ne 1 ]; then
            echo "::error Too many files - only submit one file"
            exit 1
          fi
          ./accounter-exe/accounter --database ./account.sqlite --filename $CHANGED --user ${{ github.event.pull_request.user.login }} --markdown ./README.md > ./balance.csv
          git rm $CHANGED
          git add README.md balance.csv account.sqlite
          git commit -m "ACCOUNTANT: add transaction"
          git push

